<!-- @author mengpeng -->
<!-- @email pengmeng@yangqianguan.com -->
<!-- @date 2019-08-01 15:43:46.339 -->
<!-- @desc generated by yqg-cli@1.0.9 -->

<template>
    <div class="user-group">
        <div class="card">
            <div class="form">
                <b-form
                    v-model="cond"
                    :options="FormOptions"
                    @search="onRefresh"
                >
                    <button
                        slot="actions"
                        type="button"
                        class="form-button"
                        @click="openEditModal()"
                    >
                        新增
                    </button>
                    <button
                        slot="actions"
                        type="button"
                        class="form-button"
                        @click="openUploadModal()"
                    >
                        批量新增
                    </button>
                </b-form>
            </div>
            <div class="table">
                <b-table
                    :records="records"
                    :options="TableOptions"
                >
                    <template slot="op" slot-scope="scope">
                        <button
                            class="sm primary"
                            @click="openEditModal(scope.record)"
                        >
                            修改
                        </button>

                        <button
                            class="sm primary"
                            @click="cutOff(scope.record)"
                        >
                            删除
                        </button>
                    </template>
                </b-table>
            </div>
        </div>
    </div>
</template>

<script type="text/babel">
import ClientTable from '@/common/mixin/client-table';
import FormOptions from './constant/form-options';
import TableOptions from './constant/table-options';
import EditUserGroupModal from './modal/edit-user-group-modal';
import UploadModal from './modal/upload-modal';

import Employee from '@/api/personal/employee';


export default {

    name: 'UserGroup',

    mixins: [ClientTable],

    data() {
        return {
            FormOptions,
            TableOptions
        };
    },
    mounted(){
        Employee.getList().then(res=>{
            console.log(res)
        })
    },
    methods: {
        openEditModal(record) {
            const vm = this;
            vm.$modal.open(EditUserGroupModal, {record}).then(() => {
                vm.onRefresh();
            }).catch(x => x);
        },

        cutOff() {},

        list() {
            const vm = this;
            vm.records = [{id: '1', name: '张三'},
            {id: '2', name: ' 李四'},
            {id: '3', name: '王五'},
            {id: '4', name: '王五1'},
            {id: '5', name: '王五2'},
            {id: '6', name: '王五3'},
            {id: '7', name: '王五4'},
            {id: '8', name: '王五5'},
            {id: '9', name: '王五51'},
            {id: '10', name: '王五52'},
            {id: '11', name: '王五53'}];
        },
        openUploadModal() {
            const vm = this;
            vm.$modal.open(UploadModal).then(() => {
                vm.onRefresh();
            }).catch(x => x);
        }
    }

};

</script>

<style lang="scss" rel="stylesheet/scss" scoped>
</style>
