<!-- @author mengpeng -->
<!-- @email pengmeng@yangqianguan.com -->
<!-- @date 2019-08-07 15:54:12.872 -->
<!-- @desc generated by yqg-cli@1.0.9 -->

<template>
    <b-dialog :open="visible" :close-on-click-outside="false" :title="title" @close="cancel">
        <input ref="excel-upload-input" class="excel-upload-input" type="file" accept=".xlsx, .xls" @change="handleClick">
        <div class="upload-body">
           <b-button @click="handleUpload">上传</b-button>
           <b-table :records="excelData.results"
                    :options="excelData.options"></b-table>
        </div>

        <button slot="actions" class="simple lg" @click="cancel()">
            取消
        </button>
        <button slot="actions" class="simple lg" @click="confirm()">
            确定
        </button>
    </b-dialog>
</template>

<script type="text/babel">
import XLSX from 'xlsx'

export default {
    name: 'UploadModal',
    props: {
        beforeUpload: Function, // eslint-disable-line
        onSuccess: Function// eslint-disable-line
    },
    data() {
        return {
            visible: false,

            excelData: {
                header: null,
                results: [],
                options:{colDefs:[]}
            }
        };
    },
    computed: {
        title() {
            const vm = this;
            return `批量上传`;
        }
    },
    methods: {
        handleUpload() {
            this.$refs['excel-upload-input'].click()
        },
        handleClick(e) {
            const files = e.target.files
            const rawFile = files[0] // only use files[0]
            if (!rawFile) return
            this.upload(rawFile)
        },

        upload(rawFile) {
            this.$refs['excel-upload-input'].value = null // fix can't select the same excel

            if (!this.beforeUpload) {
                this.readerData(rawFile)
                return
            }
            const before = this.beforeUpload(rawFile)
            if (before) {
                this.readerData(rawFile)
            }
        },
        readerData(rawFile) {
            this.loading = true
            return new Promise((resolve, reject) => {
                const reader = new FileReader()
                reader.onload = e => {
                    const data = e.target.result
                    const workbook = XLSX.read(data, {type: 'array'})
                    const firstSheetName = workbook.SheetNames[0]
                    const worksheet = workbook.Sheets[firstSheetName]
                    const header = this.getHeaderRow(worksheet)
                    const results = XLSX.utils.sheet_to_json(worksheet)
                    this.generateData({header, results})
                    this.loading = false
                    resolve()
                }
                reader.readAsArrayBuffer(rawFile)
            })
        },
        generateData({header, results}) {
            this.excelData.header = header
            this.excelData.options=this.getOptions(header);
            this.excelData.results = results

            this.onSuccess && this.onSuccess(this.excelData)
        },
        getOptions(header){
            const colDefs=header.map(item=>({label: item, field: item}))
            return {colDefs,enableClientPagination: true,}
        },
        getHeaderRow(sheet) {
            const headers = []
            const range = XLSX.utils.decode_range(sheet['!ref'])
            let C
            const R = range.s.r
            /* start in the first row */
            for (C = range.s.c; C <= range.e.c; ++C) { /* walk every column in the range */
                const cell = sheet[XLSX.utils.encode_cell({c: C, r: R})]
                /* find the cell in the first row */
                let hdr = 'UNKNOWN ' + C // <-- replace with your desired default
                if (cell && cell.t) hdr = XLSX.utils.format_cell(cell)
                headers.push(hdr)
            }
            return headers
        },
        isExcel(file) {
            return /\.(xlsx|xls|csv)$/.test(file.name)
        },
        cancel() {
            const vm = this;
            vm.reject();
        },

        confirm() {
            const vm = this;
            vm.resolve();
        }
    }
};

</script>
<style lang="scss">
.excel-upload-input {
    display: none;
    z-index: -9999;
}
</style>
