<!-- @author mengpeng -->
<!-- @email pengmeng@yangqianguan.com -->
<!-- @date 2019-08-07 15:54:12.872 -->
<!-- @desc generated by yqg-cli@1.0.9 -->

<template>
    <b-dialog :open="visible" :close-on-click-outside="false" :title="title" @close="cancel">
        <div class="edit-user-group-modal-body">
            <p>Body Here</p>
        </div>

        <button slot="actions" class="simple lg" @click="cancel()">
            取消
        </button>
        <button slot="actions" class="simple lg" @click="confirm()">
            确定
        </button>
    </b-dialog>
</template>

<script type="text/babel">

export default {
    name: 'EditUserGroupModal',

    props: {
        record: {
            type: Object,
            default: null
        }

    },
    data() {
        return {
            visible: false
        };
    },
    computed: {
        title() {
            const vm = this;
            return `${vm.record ? '编辑' : '新建'}用户集`;
        }
    },
    methods: {
        cancel() {
            const vm = this;
            vm.reject();
        },

        confirm() {
            const vm = this;
            vm.resolve();
        }
    }
};

</script>
